
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')
print('aaaa')

print("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")